export const listaClientes = [
    {
        cpf: "555.555.555-55",
        nomeCompleto: "Carlos Alberto dos Santos",
        endereco: "Avenida Brasil, 1000",
        cidade: "Curitiba",
        estado: "PR",
        cep: "80000-000",
    },
    {
        cpf: "666.666.666-66",
        nomeCompleto: "Fernanda Pereira de Souza",
        endereco: "Rua das Acácias, 789",
        cidade: "Florianópolis",
        estado: "SC",
        cep: "88000-000",
    },
    {
        cpf: "777.777.777-77",
        nomeCompleto: "José Eduardo da Costa",
        endereco: "Travessa dos Lírios, 432",
        cidade: "Belo Horizonte",
        estado: "MG",
        cep: "30120-001",
    },
    {
        cpf: "888.888.888-88",
        nomeCompleto: "Juliana Rodrigues Lima",
        endereco: "Rua dos Ipês, 221",
        cidade: "Rio de Janeiro",
        estado: "RJ",
        cep: "22222-333",
    },
    {
        cpf: "999.999.999-99",
        nomeCompleto: "Lucas Martins Pereira",
        endereco: "Rua dos Jasmins, 56",
        cidade: "Porto Alegre",
        estado: "RS",
        cep: "90000-111",
    },
    {
        cpf: "000.000.000-00",
        nomeCompleto: "Patrícia Almeida Costa",
        endereco: "Avenida das Palmeiras, 234",
        cidade: "São José",
        estado: "SC",
        cep: "88100-200",
    }
];
