export const listaProdutos = [
    {
        codigoProduto: "PROD001",
        descricaoProduto: "Teclado Mecânico RGB",
        categoria: "Periféricos",
        marca: "Logitech",
        modelo: "G915 TKL",
        unidadeMedida: "Unidade",
        estoque: 50,
        precoCusto: "R$ 400,00",
        precoVenda: "R$ 600,00",
        fotoProduto: "teclado_g915.jpg",
        dimensoes: "30 x 20 x 5 cm",
        peso: "1 kg",
        cor: "Preto",
        material: "Plástico e Alumínio",
        garantia: "1 ano",
        origem: "Importado",
    },
    {
        codigoProduto: "PROD002",
        descricaoProduto: "Monitor Full HD 24''",
        categoria: "Monitores",
        marca: "Dell",
        modelo: "P2419H",
        unidadeMedida: "Unidade",
        estoque: 30,
        precoCusto: "R$ 900,00",
        precoVenda: "R$ 1.200,00",
        fotoProduto: "monitor_dell_p2419h.jpg",
        dimensoes: "55 x 20 x 40 cm",
        peso: "5 kg",
        cor: "Preto",
        material: "Plástico e Metal",
        garantia: "2 anos",
        origem: "Nacional",
    },
    {
        codigoProduto: "PROD003",
        descricaoProduto: "Mouse Sem Fio",
        categoria: "Periféricos",
        marca: "Razer",
        modelo: "DeathAdder V2 Pro",
        unidadeMedida: "Unidade",
        estoque: 75,
        precoCusto: "R$ 300,00",
        precoVenda: "R$ 450,00",
        fotoProduto: "mouse_razer.jpg",
        dimensoes: "12 x 6 x 4 cm",
        peso: "150 g",
        cor: "Preto",
        material: "Plástico",
        garantia: "1 ano",
        origem: "Importado",
    },
    {
        codigoProduto: "PROD004",
        descricaoProduto: "Cadeira Gamer",
        categoria: "Móveis",
        marca: "DXRacer",
        modelo: "Formula Series",
        unidadeMedida: "Unidade",
        estoque: 20,
        precoCusto: "R$ 1.000,00",
        precoVenda: "R$ 1.500,00",
        fotoProduto: "cadeira_gamer.jpg",
        dimensoes: "70 x 70 x 130 cm",
        peso: "25 kg",
        cor: "Vermelho e Preto",
        material: "Couro Sintético e Metal",
        garantia: "1 ano",
        origem: "Nacional",
    },
    {
        codigoProduto: "PROD005",
        descricaoProduto: "SSD 1TB",
        categoria: "Armazenamento",
        marca: "Samsung",
        modelo: "970 EVO Plus",
        unidadeMedida: "Unidade",
        estoque: 100,
        precoCusto: "R$ 800,00",
        precoVenda: "R$ 1.100,00",
        fotoProduto: "ssd_samsung.jpg",
        dimensoes: "10 x 5 x 0.5 cm",
        peso: "50 g",
        cor: "Preto",
        material: "Plástico",
        garantia: "3 anos",
        origem: "Importado",
    },
    {
        codigoProduto: "PROD006",
        descricaoProduto: "Fonte de Alimentação 750W",
        categoria: "Hardware",
        marca: "Corsair",
        modelo: "RM750x",
        unidadeMedida: "Unidade",
        estoque: 40,
        precoCusto: "R$ 650,00",
        precoVenda: "R$ 850,00",
        fotoProduto: "fonte_corsair.jpg",
        dimensoes: "16 x 15 x 8.6 cm",
        peso: "1.8 kg",
        cor: "Preto",
        material: "Metal",
        garantia: "5 anos",
        origem: "Importado",
    },
];
